name: Build Geode Mod Windows

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Geode SDK
        uses: geode-sdk/setup-geode@main

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          platform: win
