name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        config:
          - { name: Windows, os: windows-latest, target: "win" }
          - { name: macOS, os: macos-latest, target: "mac" }
          - { name: Android, os: ubuntu-latest, target: "android" }

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          target: ${{ matrix.config.target }}
