name: Build Geode Mod macOS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          platform: mac
